name: Run R Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
  ACCESS_KEY: ${{ secrets.SA_ACCESS_KEY }}
  SECRET_KEY: ${{ secrets.SA_SECRET_KEY }}

jobs:
  run-r:
    runs-on: ubuntu-latest

    container:
      image: inseefrlab/onyxia-r-datascience:r4.4.1

    steps:
      - name: Checkout code with correct permissions
        uses: actions/checkout@v4
        with:
          path: repo  # on clone le dépôt dans un dossier propre

      - name: Debug – show where we are and what's inside
        run: |
          echo "Current working directory: $(pwd)"
          echo "Contents of repo directory:"
          ls -la repo

      - name: Run R script
        run: Rscript repo/generer_json.R
