name: Run R Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
  ACCESS_KEY: ${{ secrets.SA_ACCESS_KEY }}
  SECRET_KEY: ${{ secrets.SA_SECRET_KEY }}

jobs:
  run-r:
    runs-on: ubuntu-latest

    container:
      image: inseefrlab/onyxia-r-datascience:r4.4.1

    steps:
      - name: Manually clone the repository
        run: |
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          Rscript generer_json.R
