name: Run R Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
  ACCESS_KEY: ${{ secrets.SA_ACCESS_KEY }}
  SECRET_KEY: ${{ secrets.SA_SECRET_KEY }}

jobs:
  run-r:
    runs-on: ubuntu-latest

    container:
      image: inseefrlab/onyxia-r-datascience:r4.4.1

    defaults:
      run:
        working-directory: /__w/API_robot/API_robot

    steps:
      - name: Debug – show where we are
        run: |
          echo "Working directory: $(pwd)"
          echo "Files in repo:"
          ls -la

      - name: Run R script
        run: |
          Rscript generer_json.R
