name: Run R Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
  ACCESS_KEY: ${{ secrets.SA_ACCESS_KEY }}
  SECRET_KEY: ${{ secrets.SA_SECRET_KEY }}

jobs:
  run-r:
    runs-on: ubuntu-latest

    container:
      image: inseefrlab/onyxia-r-datascience:r4.4.1

    steps:
      - name: Clone the repository manually
        run: |
          mkdir -p /tmp/code
          cd /tmp/code
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} .
          ls -la

      - name: Run R script
        run: |
          cd /tmp/code
          Rscript generer_json.R
